apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: list-code
spec:
  description: >-
    ls command output
  workspaces:
    - name: response
      description: to list output
  params:
    - name: directory
      description: git url to clone
      type: string
  steps:
    - name: list-src
      image: alpine:3.12
      command:
        - "ls"
      args: 
        - "$(params.directory)"