---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pr-template
spec:
  params:
    - name: repository
      description: The git repo
    - name: apikey
      description: the ibmcloud api key
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
      default: "0"
    - name: registry-region
      description: the container registry region
    - name: registry-namespace
      description: the container registry namespace
    - name: transaction-service-image-name
      description: the image name
    - name: user-service-image-name
      description: the image name
    - name: simulator-service-image-name
      description: the image name
    - name: dev-region
      description: $(params.dev-region)
    - name: dev-resource-group
      description: $(params.dev-resource-group)
    - name: cluster-name
      description: $(params.cluster-name)
    - name: dev-cluster-namespace
      description: $(params.dev-cluster-namespace)
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.apikey)
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: cd-pipeline
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: repository
            value: $(params.repository)
          - name: branch
            value: main
          - name: registry-region
            value: $(params.registry-region)
          - name: registry-namespace
            value: $(params.registry-namespace)
          - name: transaction-service-image-name
            value: $(params.transaction-service-image-name)
          - name: user-service-image-name
            value: $(params.user-service-image-name)
          - name: simulator-service-image-name
            value: $(params.simulator-service-image-name)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
          - name: cluster-region
            value: $(params.dev-region)
          - name: resource-group
            value: $(params.dev-resource-group)
          - name: cluster-name
            value: $(params.cluster-name)
          - name: dev-cluster-namespace
            value: $(params.dev-cluster-namespace)
          - name: deployment-file
            value: deployment.yaml
          - name: path-to-transaction-svc-deployment
            value: bank-app-backend/transaction-service
          - name: path-to-user-svc-deployment
            value: bank-app-backend/user-service
          - name: path-to-transaction-service-dockerfile
            value: bank-app-backend/
          - name: path-to-user-service-dockerfile
            value: bank-app-backend/
          - name: tx-dockerfile
            value: Dockerfile.tx
          - name: user-dockerfile
            value: Dockerfile.user
          - name: directory
            value: "/workspace/response"